name: khu_farm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/splash/splash.png
    - assets/notch/morning.png
    - assets/notch/morning_right_up_cloud.png
    - assets/notch/morning_left_down_cloud.png
    - assets/mascot/login_mascot.png
    - assets/icons/goback.png
    - assets/icons/consumer.png
    - assets/icons/retailer.png
    - assets/icons/farmer.png
    - assets/mascot/main_mascot.png
    - assets/bottom_navigator/unselect/daily.png
    - assets/bottom_navigator/unselect/stock.png
    - assets/bottom_navigator/unselect/harvest.png
    - assets/bottom_navigator/unselect/laicos.png
    - assets/bottom_navigator/unselect/mypage.png
    - assets/bottom_navigator/select/daily.png
    - assets/bottom_navigator/select/stock.png
    - assets/bottom_navigator/select/harvest.png
    - assets/bottom_navigator/select/laicos.png
    - assets/bottom_navigator/select/mypage.png
    - assets/weather/cloud_sun.png
    - assets/top_icons/notice.png
    - assets/top_icons/dibs.png
    - assets/top_icons/cart.png
    - assets/top_icons/notice_selected_morning.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png
  android: true
  ios: true
  fullscreen: true